//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Location.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appartements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appartements()
        {
            this.Baux = new HashSet<Baux>();
            this.AppartementImages = new HashSet<AppartementImages>();
        }
    
        public int Id { get; set; }
        public string AdresseAppartement { get; set; }
        public Nullable<int> NbSalleBain { get; set; }
        public Nullable<int> NbEtages { get; set; }
        public string ChauffeOuiNon { get; set; }
        public Nullable<int> Annee { get; set; }
        public Nullable<int> nbBalcons { get; set; }
        public Nullable<int> nbStationnementsInt { get; set; }
        public Nullable<int> nbStationnementsExt { get; set; }
        public Nullable<int> nbGarages { get; set; }
        public string Orientation { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ImmeubleId { get; set; }
        public Nullable<int> NumeroEtage { get; set; }
        public string StatutAppartement { get; set; }
        public string TypeChauffage { get; set; }
        public Nullable<int> TypeAppartementId { get; set; }
        public Nullable<decimal> Superficie { get; set; }
        public string Titre { get; set; }
        public string Description { get; set; }
        public string Badge { get; set; }
        public string Images { get; set; }
        public Nullable<decimal> PrixPublic { get; set; }
    
        public virtual Immeubles Immeubles { get; set; }
        public virtual TypeAppartements TypeAppartements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Baux> Baux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppartementImages> AppartementImages { get; set; }
    }
}
