//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Location.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppartementImages
    {
        public int Id { get; set; }
        public int AppartementId { get; set; }
        public string ImagePath { get; set; }
        public bool IsPrimary { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Appartements Appartements { get; set; }
    }
}
