//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Location.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baux
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Baux()
        {
            this.InclusionAppareils = new HashSet<InclusionAppareils>();
            this.InclusionAutres = new HashSet<InclusionAutres>();
            this.InclusionMeubles = new HashSet<InclusionMeubles>();
            this.Payements = new HashSet<Payements>();
        }
    
        public int Id { get; set; }
        public string NumeroBail { get; set; }
        public int AppartementId { get; set; }
        public int LocataireId { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public string LieuPayement { get; set; }
        public Nullable<bool> ReglementImmeuble { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public Nullable<bool> StationnementExt { get; set; }
        public Nullable<int> NbPlacesExt { get; set; }
        public Nullable<bool> StationnementInt { get; set; }
        public Nullable<int> NbPlacesInt { get; set; }
        public string Emplacement { get; set; }
        public string RemiseEspaceRangenment { get; set; }
        public string Autre { get; set; }
        public Nullable<bool> MeublesInclus { get; set; }
        public Nullable<bool> AppareilsInclus { get; set; }
        public Nullable<bool> Deneigement { get; set; }
        public Nullable<bool> TailleGazon { get; set; }
        public Nullable<decimal> MontantDepot { get; set; }
        public Nullable<System.DateTime> DateOccupation { get; set; }
        public Nullable<System.DateTime> DateRevision { get; set; }
        public string Observation { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> DatePayement { get; set; }
        public string StatutBaux { get; set; }
        public Nullable<int> MoyenPayementId { get; set; }
        public Nullable<decimal> Charges { get; set; }
        public Nullable<System.DateTime> DateDebutEffective { get; set; }
        public Nullable<System.DateTime> DateFinEffective { get; set; }
        public Nullable<int> CoLocataireId { get; set; }
        public Nullable<System.DateTime> DateResiliation { get; set; }
    
        public virtual Appartements Appartements { get; set; }
        public virtual Baux Baux1 { get; set; }
        public virtual Baux Baux2 { get; set; }
        public virtual Baux Baux11 { get; set; }
        public virtual Baux Baux3 { get; set; }
        public virtual Locataires Locataires { get; set; }
        public virtual Locataires Locataires1 { get; set; }
        public virtual MoyenPayements MoyenPayements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InclusionAppareils> InclusionAppareils { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InclusionAutres> InclusionAutres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InclusionMeubles> InclusionMeubles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payements> Payements { get; set; }
    }
}
