//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Location.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Immeubles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Immeubles()
        {
            this.Appartements = new HashSet<Appartements>();
        }
    
        public int Id { get; set; }
        public string NomImmeuble { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string DescriptionImmeuble { get; set; }
        public string AdresseImmeuble { get; set; }
        public string StatutImmeuble { get; set; }
        public string Orientation { get; set; }
        public Nullable<int> nbEtages { get; set; }
        public Nullable<int> nbStationnementsInt { get; set; }
        public Nullable<int> nbStationnementsExt { get; set; }
        public Nullable<int> Annee { get; set; }
        public string Autre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appartements> Appartements { get; set; }
    }
}
