//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Location.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locataires
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Locataires()
        {
            this.Baux = new HashSet<Baux>();
            this.Baux1 = new HashSet<Baux>();
        }
    
        public int Id { get; set; }
        public string NomLocataire { get; set; }
        public string PrenomLocataire { get; set; }
        public string SexeLocataire { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
        public string NASLocataire { get; set; }
        public string TeLocataire { get; set; }
        public string TelSecondaire { get; set; }
        public string CourrielLocataire { get; set; }
        public string NomContactUrgence { get; set; }
        public string TelContactUrgence { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string StatutLocataire { get; set; }
        public string NomColocataire { get; set; }
        public string PrenomColocataire { get; set; }
        public string TelColocataire { get; set; }
        public string CourrielColocataire { get; set; }
        public string SexeColocataire { get; set; }
        public string StatutColocataire { get; set; }
        public string RelationLocataireColocataire { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Baux> Baux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Baux> Baux1 { get; set; }
    }
}
