//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Location.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApplicationConnection : DbContext
    {
        public ApplicationConnection()
            : base("name=ApplicationConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Appareils> Appareils { get; set; }
        public virtual DbSet<Appartements> Appartements { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AutresObjets> AutresObjets { get; set; }
        public virtual DbSet<Baux> Baux { get; set; }
        public virtual DbSet<Immeubles> Immeubles { get; set; }
        public virtual DbSet<InclusionAppareils> InclusionAppareils { get; set; }
        public virtual DbSet<InclusionAutres> InclusionAutres { get; set; }
        public virtual DbSet<InclusionMeubles> InclusionMeubles { get; set; }
        public virtual DbSet<Locataires> Locataires { get; set; }
        public virtual DbSet<Locateur> Locateur { get; set; }
        public virtual DbSet<Meubles> Meubles { get; set; }
        public virtual DbSet<MoyenPayements> MoyenPayements { get; set; }
        public virtual DbSet<Payements> Payements { get; set; }
        public virtual DbSet<RefMessages> RefMessages { get; set; }
        public virtual DbSet<TypeAppartements> TypeAppartements { get; set; }
        public virtual DbSet<AppartementImages> AppartementImages { get; set; }
        public virtual DbSet<v_Factures_Locataire> v_Factures_Locataire { get; set; }
        public virtual DbSet<V_Payements> V_Payements { get; set; }
    }
}
