//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Location.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payements
    {
        public int Id { get; set; }
        public Nullable<int> Annee { get; set; }
        public Nullable<int> Mois { get; set; }
        public Nullable<System.DateTime> DatePayement { get; set; }
        public string LieuPayement { get; set; }
        public string Description { get; set; }
        public string ModePayement { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> BauxId { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public string Statut { get; set; }
        public Nullable<int> MoyenPayementId { get; set; }
    
        public virtual Baux Baux { get; set; }
        public virtual MoyenPayements MoyenPayements { get; set; }
    }
}
