//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Location.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Payements
    {
        public int NumeroFacture { get; set; }
        public string Adresse { get; set; }
        public string NomCompletLocataire { get; set; }
        public string NomCompletCoLocataire { get; set; }
        public Nullable<int> Annee { get; set; }
        public Nullable<int> Mois { get; set; }
        public Nullable<System.DateTime> DatePayement { get; set; }
        public string LieuPayement { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public string NomMoyenPayement { get; set; }
        public string Description { get; set; }
    }
}
